### ISSUE TITLE
Want logo for MozUI

### ISSUE THREAD

**Issue by learneradarsh** [MozillaKNITOpenSource/MozUI#1]
A better logo which can show open source and perfection of UI and Ux both.

**Comment by BH12ri** [comment]
![logo1](https://cloud.githubusercontent.com/assets/27543142/26760492/34e41c84-4937-11e7-97d3-8b11960222bc.png)
![logo](https://cloud.githubusercontent.com/assets/27543142/26760498/4971db46-4937-11e7-9f26-f93eee9d81dd.png)

**Comment by learneradarsh** [comment]
** Final logo for MozUI **
![image](https://user-images.githubusercontent.com/18267421/27338512-035a87d4-55f3-11e7-8f24-9ae009f7b0af.png)
